### ISSUE TITLE
pcsx-rearmed-libretro fails building on raspberry

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#62] opened 2017-03-11 14:14 UTC
It fails because of the following errors : 

libpcsxcore/new_dynarec/backends/psx/emu_if.o: In function `ari64_init':
emu_if.c:(.text+0x420): undefined reference to `gteRTPS_neon'
emu_if.c:(.text+0x424): undefined reference to `gteRTPT_neon'
frontend/libretro.o: In function `vout_flip':
libretro.c:(.text+0x278): undefined reference to `bgr888_to_rgb565'

For whatever reason, the ebuild script won't build libpcsxcore/gte_neon.S and frontend/cspace_neon.S, which i think is the cause of this issue

Building it outside of portage work.

**Comment by stefan-gr** [comment] 2017-03-12 06:59
I think it's because of the configure script, let's see if moving everything to makefile will change anything.

**Comment by stefan-gr** [comment] 2017-03-12 07:20
Please try again, I moved everything to makefile and dropped the stdint patch. I used the occasion to put arm keywords to more ebuilds that make sense without testing so you can probably drop your own keywords for some ebuilds.
I'm not sure if the USE="neon" flag works as expected now.

**Comment by barbudreadmon** [comment] 2017-03-12 09:37
Building with the neon use flag enabled works as expected, disabling it cause the same issue as above, probably because the neon part in the cflags enable some C macro.
I see 2 ways of fixing this second issue : 
- filter out neon cflags when neon use flag is disabled.
- keep the configure script, remove the neon use flag (which shouldn't be needed since the configure script enable HAVE_NEON depending on cflags) and figure out why it won't build some files, here is the generated config.mak if it can help (inside and outside portage generate exactly the same) : 

`CC = gcc
CXX = g++
AS = as
CFLAGS += -O2 -pipe -march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard -fPIC -D_FILE_OFFSET_BITS=64 -Wno-unused-result
ASFLAGS +=  -mfpu=neon
LDFLAGS += 
MAIN_LDFLAGS +=  -shared -Wl,--no-undefined
MAIN_LDLIBS += -lpng  -ldl -lm -lpthread -lz
PLUGIN_CFLAGS +=  -fPIC

TARGET = libretro.so
ARCH = arm
PLATFORM = libretro
BUILTIN_GPU = neon
SOUND_DRIVERS = libretro
PLUGINS = plugins/spunull/spunull.so plugins/dfxvideo/gpu_peops.so plugins/gpu_unai/gpu_unai.so plugins/gpu-gles/gpu_gles.so
HAVE_NEON = 1
HAVE_GLES = 1
CFLAGS_GLES =  -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
LDLIBS_GLES = -lEGL -lGLESv1_CM  -L/opt/vc/lib -lbcm_host
USE_DYNAREC = 1`

seems to me like 'ifeq "$(HAVE_NEON)" "1"' at lines 58, 149 and 216 of Makefile are not doing their job properly, but i don't understand why.

**Comment by stefan-gr** [comment] 2017-03-12 09:40
`ARCH = arm`
is probably the culprit. I just committed some change to rename that variable since Gentoo already sets it. Please try again with at least ee95c375caeaccf70f1c21a565c439e073678bcf

**Comment by barbudreadmon** [comment] 2017-03-12 10:00
Now the ebuild is failing again, whatever the USE flags, with the following error : 

libpcsxcore/new_dynarec/backends/psx/emu_if.o: In function `ari64_init':
emu_if.c:(.text+0x418): undefined reference to `gteNCLIP_arm'
plugins/dfsound/spu.o: In function `spu_worker_thread':
spu.c:(.text+0x1da4): undefined reference to `mix_chan'
spu.c:(.text+0x1f68): undefined reference to `mix_chan_rvb'
plugins/dfsound/spu.o: In function `do_samples':
spu.c:(.text+0x2588): undefined reference to `mix_chan'
spu.c:(.text+0x27a4): undefined reference to `mix_chan_rvb'
collect2: error: ld returned 1 exit status
Makefile:269: recipe for target 'pcsx_rearmed_libretro.so' failed

It seems related to libpcsxcore/gte_arm.o not being built (which depends on a 'ifeq "$(ARCH)" "arm"' in Makefile)

**Comment by barbudreadmon** [comment] 2017-03-12 10:03
My bad, it could be related to building the 9999-r2 version with "games-emulation/pcsx-rearmed-libretro **" in my keywords

**Comment by barbudreadmon** [comment] 2017-03-12 10:13
No, i confirm this issue without "games-emulation/pcsx-rearmed-libretro **" in my keywords, it seems ARCH = arm is needed

**Comment by stefan-gr** [comment] 2017-03-12 11:37
Problem is, gentoo overwrites ARCH with emake. Making that variable useless since it only fills it with the current arch it has in your profile. I attempted to include configure this time and hope it turns out better now.

**Comment by barbudreadmon** [comment] 2017-03-12 13:31
Now i have all the errors at the same time

**Comment by stefan-gr** [comment] 2017-03-12 13:54
Now we are using standard configure and completely ignore Makefile.libretro. How does that work out?

**Comment by barbudreadmon** [comment] 2017-03-12 14:55
building with neon use flag, failing without it, i think you can safely remove it now since enabling or disabling neon support is properly configured through the configure script

**Comment by stefan-gr** [comment] 2017-03-12 15:26
I will remove it then and make configure into a stub since Makefile.libretro doesn't seem to depend on it and it should autodetect neon too. That makefile also produces fewer errors on my machine.
Please take a look.

**Comment by barbudreadmon** [comment] 2017-03-12 16:01
the first issue came back, i think we should stick to ./configure + normal Makefile + no neon use flags

**Comment by barbudreadmon** [comment] 2017-03-12 16:05
This is also what retropie is doing (for every arch) : https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/libretrocores/lr-pcsx-rearmed.sh

**Comment by stefan-gr** [comment] 2017-03-12 16:23
Now I'm eager to see the results.

**Comment by barbudreadmon** [comment] 2017-03-12 17:03
Building fine here, and it detects neon support. If i was picky i would say "$(use_enable arm dynarec )" is probably unneeded considering"configure" probably detect if dynarec is needed from cflags, but that's not 100% sure and not fixing something which is not broken seems fine.

**Closed** 2017-03-12 17:10 UTC

**Comment by stefan-gr** [comment] 2017-03-12 17:13
Finally fixed it seems. It was basically caused by the eclass change using Makefile.libretro.
Thanks for testing. Some day I will get an rpi too and can test things myself.
